import { WORK_STATUS } from './model.mjs';

// ข้อมูลจำลองสำหรับทดสอบ UI เท่านั้น ไม่ใช่ข้อมูลโครงการจริงของหน่วยงาน
export const PILOT_ORGANIZATION_ID = 'ORG-PILOT';

export const constructionPilotProjects = [
  {
    id: 'CON-2569-001',
    organizationId: PILOT_ORGANIZATION_ID,
    department: 'กองช่าง',
    projectType: 'ก่อสร้างถนน',
    name: 'ปรับปรุงผิวจราจรถนนสายตัวอย่าง A',
    owner: 'เจ้าหน้าที่ผู้รับผิดชอบ 1',
    location: 'พื้นที่ตัวอย่าง ตำบล A',
    contractNo: 'สญ.ตัวอย่าง-001/2569',
    contractor: 'ผู้รับจ้างตัวอย่าง A',
    budget: 4800000,
    spent: 2100000,
    plannedProgress: 82,
    actualProgress: 54,
    startDate: '2026-06-01',
    dueDate: '2026-09-15',
    status: WORK_STATUS.IN_PROGRESS,
    lastUpdatedAt: '2026-08-24',
    problem: 'ความก้าวหน้าต่ำกว่าแผน ต้องติดตามแผนเร่งรัดงาน',
  },
  {
    id: 'CON-2569-002',
    organizationId: PILOT_ORGANIZATION_ID,
    department: 'กองช่าง',
    projectType: 'อาคาร',
    name: 'ปรับปรุงอาคารบริการประชาชนตัวอย่าง',
    owner: 'เจ้าหน้าที่ผู้รับผิดชอบ 2',
    location: 'พื้นที่ตัวอย่าง ตำบล B',
    contractNo: 'สญ.ตัวอย่าง-002/2569',
    contractor: 'ผู้รับจ้างตัวอย่าง B',
    budget: 3200000,
    spent: 2600000,
    plannedProgress: 88,
    actualProgress: 84,
    startDate: '2026-05-15',
    dueDate: '2026-09-25',
    status: WORK_STATUS.IN_PROGRESS,
    lastUpdatedAt: '2026-08-25',
    problem: '',
  },
  {
    id: 'CON-2569-003',
    organizationId: PILOT_ORGANIZATION_ID,
    department: 'กองช่าง',
    projectType: 'ระบายน้ำ',
    name: 'ก่อสร้างรางระบายน้ำพื้นที่ตัวอย่าง',
    owner: 'เจ้าหน้าที่ผู้รับผิดชอบ 3',
    location: 'พื้นที่ตัวอย่าง ตำบล C',
    contractNo: 'สญ.ตัวอย่าง-003/2569',
    contractor: 'ผู้รับจ้างตัวอย่าง C',
    budget: 2100000,
    spent: 600000,
    plannedProgress: 62,
    actualProgress: 46,
    startDate: '2026-07-01',
    dueDate: '2026-10-05',
    status: WORK_STATUS.IN_PROGRESS,
    lastUpdatedAt: '2026-08-20',
    problem: 'รอปรับแผนการเข้าพื้นที่บางช่วง',
  },
  {
    id: 'CON-2569-004',
    organizationId: PILOT_ORGANIZATION_ID,
    department: 'กองช่าง',
    projectType: 'สะพาน',
    name: 'ซ่อมแซมสะพานคอนกรีตตัวอย่าง',
    owner: 'เจ้าหน้าที่ผู้รับผิดชอบ 1',
    location: 'พื้นที่ตัวอย่าง ตำบล D',
    contractNo: 'สญ.ตัวอย่าง-004/2569',
    contractor: 'ผู้รับจ้างตัวอย่าง D',
    budget: 1750000,
    spent: 700000,
    plannedProgress: 70,
    actualProgress: 38,
    startDate: '2026-06-20',
    dueDate: '2026-09-03',
    status: WORK_STATUS.BLOCKED,
    lastUpdatedAt: '2026-08-21',
    problem: 'มีประเด็นหน้างานที่ต้องเร่งแก้ไขก่อนเดินงานต่อ',
  },
  {
    id: 'CON-2569-005',
    organizationId: PILOT_ORGANIZATION_ID,
    department: 'กองช่าง',
    projectType: 'ก่อสร้างถนน',
    name: 'ก่อสร้างถนนคอนกรีตสายตัวอย่าง B',
    owner: 'เจ้าหน้าที่ผู้รับผิดชอบ 4',
    location: 'พื้นที่ตัวอย่าง ตำบล E',
    contractNo: 'สญ.ตัวอย่าง-005/2569',
    contractor: 'ผู้รับจ้างตัวอย่าง E',
    budget: 5400000,
    spent: 5400000,
    plannedProgress: 100,
    actualProgress: 100,
    startDate: '2026-03-01',
    dueDate: '2026-07-31',
    status: WORK_STATUS.COMPLETED,
    lastUpdatedAt: '2026-08-05',
    problem: '',
  },
  {
    id: 'CON-2569-006',
    organizationId: PILOT_ORGANIZATION_ID,
    department: 'กองช่าง',
    projectType: 'ไฟฟ้า',
    name: 'ติดตั้งระบบไฟสาธารณะพื้นที่ตัวอย่าง',
    owner: 'เจ้าหน้าที่ผู้รับผิดชอบ 5',
    location: 'พื้นที่ตัวอย่าง ตำบล F',
    contractNo: 'สญ.ตัวอย่าง-006/2569',
    contractor: 'ผู้รับจ้างตัวอย่าง F',
    budget: 980000,
    spent: 0,
    plannedProgress: 10,
    actualProgress: 0,
    startDate: '2026-08-20',
    dueDate: '2026-11-30',
    status: WORK_STATUS.NOT_STARTED,
    lastUpdatedAt: '2026-08-22',
    problem: 'อยู่ระหว่างเตรียมเข้าพื้นที่',
  },
  {
    id: 'CON-2569-007',
    organizationId: PILOT_ORGANIZATION_ID,
    department: 'กองช่าง',
    projectType: 'อาคาร',
    name: 'ปรับปรุงอาคารศูนย์บริการตัวอย่าง',
    owner: 'เจ้าหน้าที่ผู้รับผิดชอบ 2',
    location: 'พื้นที่ตัวอย่าง ตำบล G',
    contractNo: 'สญ.ตัวอย่าง-007/2569',
    contractor: 'ผู้รับจ้างตัวอย่าง G',
    budget: 1450000,
    spent: 1320000,
    plannedProgress: 100,
    actualProgress: 100,
    startDate: '2026-04-15',
    dueDate: '2026-08-20',
    status: WORK_STATUS.WAITING_REVIEW,
    lastUpdatedAt: '2026-08-25',
    problem: 'รอตรวจรับงาน',
  },
  {
    id: 'CON-OTHER-001',
    organizationId: 'ORG-OTHER',
    department: 'กองช่าง',
    projectType: 'ก่อสร้างถนน',
    name: 'ข้อมูลจำลองขององค์กรอื่นเพื่อทดสอบ tenant isolation',
    owner: 'ผู้ใช้ตัวอย่าง',
    budget: 9999999,
    spent: 0,
    plannedProgress: 50,
    actualProgress: 0,
    dueDate: '2026-09-01',
    status: WORK_STATUS.BLOCKED,
    lastUpdatedAt: '2026-08-01',
    problem: 'รายการนี้ต้องไม่ปรากฏใน dashboard ของ ORG-PILOT',
  },
];
